{% set name = "json2parquet" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 080dcbacc10c8655528f0318d24f2d9fc7bb59b3c5126caaea80938e4f6bbf49

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ciso8601
    - numpy >=1.14.0
    - pandas <2.0.0
    - pyarrow <6.0.0
    - python >=3.6

test:
  imports:
    - json2parquet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andrewgross/json2parquet
  summary: A simple Parquet converter for JSON/python data
  description: This library wraps pyarrow to provide some tools to easily convert JSON data into Parquet format. It is mostly in Python. It iterates over files. It copies the data several times in memory. It is not meant to be the fastest thing available. However, it is convenient for smaller data sets, or people who don't
    have a huge issue with speed.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/andrewgross/json2parquet

extra:
  recipe-maintainers:
    - BastianZim
